Add tests for sub_group_mask non const member functions
KhronosGroup/SYCL-CTS pull request #204
Opened 2021-10-18 12:41 UTC by vasilytric

`sub_group_mask` it's an extension, documentations can be found here: [intel/llvm/doc/SubGroupMask](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/SubGroupMask/SubGroupMask.asciidoc)

This PR depends on https://github.com/KhronosGroup/SYCL-CTS/pull/200
`sub_group_mask_common.h` file can be found in PR#200

2021-11-09 04:07 UTC, keryell commented
Let's wait for https://github.com/KhronosGroup/SYCL-CTS/pull/200 to settle first.

2021-11-23 06:01 UTC, keryell requested changes

2021-11-24 08:51 UTC, vasilytric commented on tests/sub_group_mask/sub_group_mask_flip_api.cpp
> +    return ((before_flip ^ after_flip) == ~zero);
I've applied this comment [here](https://github.com/KhronosGroup/SYCL-CTS/pull/204/commits/e0e16fd8448171d1f08e22319ccdfb60e1a4bddd#diff-d1406ca25ff16af0b829e9a90174b01dcdd9f99ab13e22500ecbdc808388982bR25)

2021-11-24 08:51 UTC, vasilytric commented on tests/sub_group_mask/sub_group_mask_flip_api.cpp
> +    unsigned long zero = 0;
I've applied this comment [here](https://github.com/KhronosGroup/SYCL-CTS/pull/204/commits/e0e16fd8448171d1f08e22319ccdfb60e1a4bddd#diff-d1406ca25ff16af0b829e9a90174b01dcdd9f99ab13e22500ecbdc808388982bL22)

2021-11-24 08:51 UTC, vasilytric commented on tests/sub_group_mask/sub_group_mask_flip_id.cpp
> +    return ((before_flip ^ after_flip) == 1 << local_id.get(0));
I've applied this comment [here](https://github.com/KhronosGroup/SYCL-CTS/pull/204/commits/e0e16fd8448171d1f08e22319ccdfb60e1a4bddd#diff-cd29a5aef461102303f5e5a6bbbc310d462415fd23fbbb2097d3afd60ab2d68aL26-L27)

2021-11-24 08:51 UTC, vasilytric commented on tests/sub_group_mask/sub_group_mask_set_api.cpp
> +    return (after_set == ~zero);
I've applied this comment [here](https://github.com/KhronosGroup/SYCL-CTS/pull/204/commits/e0e16fd8448171d1f08e22319ccdfb60e1a4bddd#diff-fd207f571e1fb3ff3a62fa729e3085e112aec215995fd5ca82575f5bfd9d6fb5L25-L26)

2021-11-24 08:51 UTC, vasilytric commented on tests/sub_group_mask/sub_group_mask_reset_low.cpp
> +    return ((after_reset ^ before_reset) == 1 << low);
I've applied this comment [here](https://github.com/KhronosGroup/SYCL-CTS/pull/204/commits/e0e16fd8448171d1f08e22319ccdfb60e1a4bddd#diff-7538ac13065e2c4e4b0d3e836b62afdbce0dd7335a1b33034a60decd70345077L26-L27)

2021-11-24 08:51 UTC, vasilytric commented on tests/sub_group_mask/sub_group_mask_reset_id.cpp
> +          break;
I've applied this comment [here](https://github.com/KhronosGroup/SYCL-CTS/pull/204/commits/e0e16fd8448171d1f08e22319ccdfb60e1a4bddd#diff-d8d6ab904bdaf32fee120080f848f249ca7fd8fb7955c9022d4efe09fc79d939L29-L30)

2021-11-24 08:51 UTC, vasilytric commented on tests/sub_group_mask/sub_group_mask_reset_api.cpp
> +    return (after_reset == 0);
I've applied this comment [here](https://github.com/KhronosGroup/SYCL-CTS/pull/204/commits/e0e16fd8448171d1f08e22319ccdfb60e1a4bddd#diff-2fc771cf626670244d53a9352068abcb1a48fd10ba64e7e30b5ab835c59f1a44L24-L25)

2021-11-24 08:51 UTC, vasilytric commented on tests/sub_group_mask/sub_group_mask_reset_id.cpp
> +    }
> I am trying to understand your code obfuscation contest :-)

Oh, unfortunately, some statement of these test could be so obfuscated

I've applied this comment [here](https://github.com/KhronosGroup/SYCL-CTS/pull/204/commits/e0e16fd8448171d1f08e22319ccdfb60e1a4bddd#diff-d8d6ab904bdaf32fee120080f848f249ca7fd8fb7955c9022d4efe09fc79d939L21-L23)

2021-11-24 08:56 UTC, vasilytric commented
@keryell  I am sorry for the force-push
I decide to do it due to the fact my previous push contained unintended commits

2021-12-01 06:59 UTC, vasilytric commented on tests/sub_group_mask/sub_group_mask_reset_high.cpp
> +    return ((after_reset ^ before_reset) == 1 << high);
Comment was applied [here](https://github.com/KhronosGroup/SYCL-CTS/pull/204/commits/e0e16fd8448171d1f08e22319ccdfb60e1a4bddd#diff-001baad40d55a09bfbd12a47c7400f5fe59dee60da9ec86e2ec75ba46f5f889bR26)

2022-01-06 13:23 UTC, keryell reviewed
It should be good when it is merged from main branch to move into subdirectories, once https://github.com/KhronosGroup/SYCL-CTS/pull/200 has landed.

2022-01-10 16:59 UTC, keryell approved these changes
Good!

2022-01-12 10:36 UTC, merged