Functional test for extension oneapi::device_global. Interaction with kernel bundle.
KhronosGroup/SYCL-CTS pull request #263
Opened 2022-01-31 08:39 UTC by AndreyXRomanov

This PR provides a functional test for `device_global`:
Tests interaction with kernel bundle

Link to changes related to this PR.

2022-02-01 00:23 UTC, keryell requested changes

2022-02-01 00:23 UTC, keryell commented on tests/extension/oneapi_device_global/device_global_common.h
> +   * @param value The reference to the array that needs to be change
Cf same changes in previous PR

2022-02-01 03:57 UTC, AndreyXRomanov commented on tests/extension/oneapi_device_global/device_global_common.h
> +   * @param value The reference to the array that needs to be change
Applied comments from previous PR

2022-02-03 16:06 UTC, ProGTX approved these changes

2022-02-04 02:35 UTC, keryell approved these changes
Thanks.

2022-02-04 07:36 UTC, merged