Add tests for async_handler
KhronosGroup/SYCL-CTS pull request #313
Opened 2022-03-30 09:17 UTC by kopylovanat

Tests for [2.6. sycl::async_handler](https://github.com/KhronosGroup/SYCL-CTS/blob/SYCL-2020/test_plans/exceptions.asciidoc#26-syclasync_handler)

2022-03-31 12:40 UTC, keryell requested changes
Looks good.

2022-03-31 12:40 UTC, keryell commented on tests/exceptions/exceptions_async_handler.cpp
> +    "Check that when there are no exceptions expected then the async handler "
```suggestion
    "Check that, when there is no exception expected, the async handler "
```

2022-03-31 12:40 UTC, keryell commented on tests/exceptions/exceptions_async_handler.cpp
> +    std::vector<sycl::event> event_vector(1, event);
Think Python :-)
```suggestion
    std::vector event_vector { event };
```

2022-03-31 13:00 UTC, ProGTX approved these changes

2022-04-01 06:41 UTC, kopylovanat commented on tests/exceptions/exceptions_async_handler.cpp
> +    "Check that when there are no exceptions expected then the async handler "
Done.

2022-04-01 06:41 UTC, kopylovanat commented on tests/exceptions/exceptions_async_handler.cpp
> +    std::vector<sycl::event> event_vector(1, event);
Thank you! Done.

2022-04-07 23:16 UTC, keryell approved these changes
Thanks.

2022-04-14 00:23 UTC, merged