Substitute deprecated feature kernel::get_work_group_info with kernel::get_info
KhronosGroup/SYCL-CTS pull request #367
Opened 2022-07-26 17:35 UTC by raaiq1

SYCL 2020 specification doesn't include kernel::get_work_group_info, thus calls to such methods in the tests are replaced with kernel::get_info

2022-07-26 17:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/SYCL-CTS?pullRequest=367) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/SYCL-CTS?pullRequest=367) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/SYCL-CTS?pullRequest=367) it.</sub>

2022-07-27 08:19 UTC, bader approved these changes

2022-07-27 13:36 UTC, bader requested changes
@raaiq1, please, disable build of failing tests in CI. It seems that ComputeCPP version we use doesn't support new SYCL 2020 API yet.

2022-07-28 14:55 UTC, keryell approved these changes

2022-07-29 11:03 UTC, merged