Remove library dependency on OpenCL
KhronosGroup/SYCL-CTS pull request #393
Opened 2022-11-03 10:41 UTC by psalz

Include OpenCL headers via submodule (we still require these for reference math implementation), unless OpenCL interop testing is enabled.

Fixes #347.

2022-11-03 11:43 UTC, keryell approved these changes
Thanks.

2022-11-03 11:44 UTC, bader requested changes

2022-11-03 11:44 UTC, bader commented on cmake/FindDPCPP.cmake
> +#   INTERFACE_LINK_LIBRARIES    OpenCL::OpenCL
```suggestion
```

2022-11-03 13:23 UTC, bader approved these changes

2022-11-03 13:23 UTC, bader commented on CMakeLists.txt
> +if(SYCL_CTS_ENABLE_OPENCL_INTEROP_TESTS OR SYCL_IMPLEMENTATION STREQUAL "ComputeCpp")
Could you add a comment here with the clarification why ComputeCPP case is special?

2022-11-03 14:04 UTC, psalz commented
Okay, I went back to the drawing board and chose a different route. I'm now defining a proxy library (`CTS::OpenCL_Proxy`), which allows me to transitively set `CL_TARGET_OPENCL_VERSION=120` on all targets that include the OpenCL header. This finally suppresses the warning `"CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 300 (OpenCL 3.0)"` which we've been emitting for ages.

2022-11-03 14:32 UTC, bader approved these changes
Looks good to me.
Nitpick: "Remove library dependency on OpenCL" sounds too ambitious after recent two re-bases. :)

2022-11-10 08:58 UTC, keryell approved these changes
Nice!

2022-11-10 16:35 UTC, tomdeakin commented
@ProGTX please review, merge is accepted.

2022-11-10 16:35 UTC, ProGTX approved these changes

2022-11-10 16:47 UTC, merged