[SYCL] Fix group_broadcast test for Boolean data type
KhronosGroup/SYCL-CTS pull request #607
Opened 2023-04-20 17:29 UTC by uditagarwal97

Currently, the group_broadcast test fails for boolean variables.

2023-04-20 17:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/SYCL-CTS?pullRequest=607) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/SYCL-CTS?pullRequest=607) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/SYCL-CTS?pullRequest=607) it.</sub>

2023-05-10 00:22 UTC, keryell requested changes

2023-05-10 00:22 UTC, keryell commented on tests/group_functions/group_broadcast.h
>            // return the sub-group size
```suggestion
          // Return the sub-group size when possible or just its parity
```

2023-05-10 00:33 UTC, bader commented on tests/group_functions/group_broadcast.h
> +          if (sub_group.get_local_linear_id() == 0){
```suggestion
          if (sub_group.get_local_linear_id() == 0) {
```

2023-05-11 15:21 UTC, tomdeakin commented
Looks like changes still in progress. Please finish, and review.

2023-05-13 01:24 UTC, keryell approved these changes
Thanks!

2023-05-13 01:26 UTC, merged