Fix type pack creation for atomic_ref tests
KhronosGroup/SYCL-CTS pull request #666
Opened 2023-05-26 09:03 UTC by vladimirkhashev

Because of type long can have size greater than 32 bits added checking of its size. Now this type is included in `atomic64` type pack if its size greater than 4 bytes.

2023-06-02 18:38 UTC, keryell requested changes

2023-06-02 18:38 UTC, keryell commented on tests/atomic_ref/atomic_ref_common.h
> +  if constexpr (sizeof(long) > 32) {
It might be possible on an FPGA... ;-)
Comments.

2023-06-02 18:39 UTC, keryell commented on tests/atomic_ref/atomic_ref_common.h
> +  if constexpr (sizeof(long) > 32) {
Typically the information from the PR descriptions should appear somehow as comment in the code to be clearer to read.

2023-06-05 18:10 UTC, vladimirkhashev commented on tests/atomic_ref/atomic_ref_common.h
> +  if constexpr (sizeof(long) == 32) {
Fixed. I'm talking about `long` here, according to c++ standard `long` might to be at least 32 bits or wider, so if this type is grater than 4 bytes we should perform `atomic_ref` tests with this type only if device supports `atomic64` aspect. Added comments.

2023-06-07 22:58 UTC, bader approved these changes

2023-06-08 15:45 UTC, ProGTX approved these changes

2023-06-23 16:59 UTC, keryell approved these changes
Great clarification!

2023-06-23 17:44 UTC, merged