Added check for result correctness for Geometric functions
KhronosGroup/SYCL-CTS pull request #81
Opened 2021-03-18 14:06 UTC by kopylovanat

Also covered previously missed gap - type double for geometric functions

Depends on PR https://github.com/KhronosGroup/SYCL-CTS/pull/78
Only last commit https://github.com/KhronosGroup/SYCL-CTS/commit/5741347753a3aa75ce688a2948d929d57b419515 for this PR

2021-04-08 15:47 UTC, ProGTX approved these changes

2021-04-08 17:27 UTC, keryell requested changes
That looks good.
Just a few details.

2021-04-12 08:25 UTC, kopylovanat commented on util/math_reference.cpp
> +  if (a.i & 0x8000)
Added comments.

2021-04-13 05:46 UTC, kopylovanat commented on tests/math_builtin_api/modules/sycl_functions.py
> +    f_cross = funsig("cl::sycl", "cl::sycl::float3", "cross", ["cl::sycl::float3", "cl::sycl::float3"], "3") # cumulative error for multiplications and substruction
Added displaying accuracy comments if something goes wrong

2021-04-14 03:02 UTC, keryell requested changes
Thanks, quite clearer.
There are still some obscure details...

2021-04-14 03:02 UTC, keryell commented on util/math_reference.cpp
> +  a = (a < 0) ? (int16_t)0x8000 - a : a;
Not clear what this is doing. Perhaps something like:
`// Convert again a from 2-complement signed value into sign bit + unsigned value`

2021-04-15 04:02 UTC, keryell approved these changes
Thanks!

2021-04-15 07:00 UTC, merged