template specialization for event_generator<bool, buf_size>
KhronosGroup/SYCL-CTS pull request #827
Opened 2023-11-03 07:47 UTC by ChengChen002

2023-11-03 08:17 UTC, ChengChen002 commented
I haven't come up with a cleaner way to fix this yet, please comment if you have any other suggestions! Thanks.

2023-11-03 16:04 UTC, bader commented
> I haven't come up with a cleaner way to fix this yet, please comment if you have any other suggestions! Thanks.

Please, push "Ready for review" button if you want this PR to be reviewed.

2023-11-04 01:59 UTC, keryell reviewed
This looks correct but there is a lot of code duplication.
I was thinking about introducing a generic container type that would select either a `std::vector` or a `std::array` according to the value type, but thinking again, why not just using always a `std::array`?

2023-11-06 03:21 UTC, ChengChen002 commented
> This looks correct but there is a lot of code duplication. I was thinking about introducing a generic container type that would select either a `std::vector` or a `std::array` according to the value type, but thinking again, why not just using always a `std::array`?

This is to avoid using too much stack memory, you can see more information in #823.

2023-11-08 02:32 UTC, keryell approved these changes
Thanks! I love shorter code for maintenance. :-)

2023-11-08 02:36 UTC, keryell requested changes

2023-11-08 02:36 UTC, keryell commented on tests/usm/usm_api.h
> +                                                unsigned char, T>::type;
C++14
```suggestion
  using ContainType = typename std::conditional_t<std::is_same_v<bool, T>,
                                                unsigned char, T>;
```

2023-11-08 03:00 UTC, bader commented on tests/usm/usm_api.h
> +                                                  unsigned char, T>;
```suggestion
  using ContainType =
      typename std::conditional_t<std::is_same_v<bool, T>, unsigned char, T>;
```

2023-11-09 15:50 UTC, keryell approved these changes
Thanks!

2023-11-09 16:01 UTC, merged