Added Aarch64 support to oclmath library
KhronosGroup/SYCL-CTS pull request #921
Opened 2024-07-31 12:58 UTC by lrpablo

Added support for Aarch64

2024-07-31 12:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/SYCL-CTS?pullRequest=921) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/SYCL-CTS?pullRequest=921) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/SYCL-CTS?pullRequest=921) it.</sub>

2024-07-31 21:17 UTC, bader requested changes

2024-07-31 21:17 UTC, bader commented on oclmath/fpcontrol.h
> +#elif defined (__arm__)
```suggestion
#elif defined (__arm__)
```
Please, no trailing whitespaces.

2024-07-31 21:17 UTC, bader commented on oclmath/reference_math.cpp
> +#elif defined(__arm__)  || defined( __aarch64__ )// ARM .. sizeof(long double) == sizeof(double)
```suggestion
#elif defined(__arm__)  || defined( __aarch64__ ) // ARM .. sizeof(long double) == sizeof(double) 
```

2024-07-31 21:17 UTC, bader commented on oclmath/rounding_mode.cpp
> +        #error Unknown arch 1
What is the value of this change?

2024-07-31 21:17 UTC, bader commented on oclmath/rounding_mode.cpp
> +        #define _FPU_SETCW(cw) __asm__ ("MSR FPCR,%0" : :"ri" (cw))
```suggestion
        #define _ARM_FE_FTZ     0x1000000
    		#define _ARM_FE_NFTZ    0x0
        #define _FPU_SETCW(cw) __asm__ ("MSR FPCR,%0" : :"ri" (cw))
```

NOTE: your change invalidates the branch for `__arm__` case by removing
```c++
		static const int ftz_modes[ kRoundingModeCount ] = { _ARM_FE_FTZ, _ARM_FE_NFTZ };
		const int *f = ftz_modes;
		_FPU_SETCW( f[1] );
```

The same applies to `FlushToZero` function.

2024-07-31 21:37 UTC, bader commented
@lrpablo, we already have https://github.com/KhronosGroup/SYCL-CTS/pull/890, which is supposed to do the same improvement. 
@hvdijk, FYI.

2024-08-01 08:28 UTC, lrpablo commented
Okay, I hadn't seen that. My apologies for the inconvenience. Do you have an estimated date for when it will be present in the release?

Regards and thank you,

________________________________
From: Alexey Bader ***@***.***>
Sent: 31 July 2024 22:37
To: KhronosGroup/SYCL-CTS ***@***.***>
Cc: Pablo ***@***.***>; Mention ***@***.***>
Subject: Re: [KhronosGroup/SYCL-CTS] Added Aarch64 support to oclmath library (PR #921)


@lrpablo<https://github.com/lrpablo>, we already have #890<https://github.com/KhronosGroup/SYCL-CTS/pull/890>, which is supposed to do the same improvement.
@hvdijk<https://github.com/hvdijk>, FYI.

—
Reply to this email directly, view it on GitHub<https://github.com/KhronosGroup/SYCL-CTS/pull/921#issuecomment-2261503935>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BE6TABJPGITRCW533SJILCTZPFKJFAVCNFSM6AAAAABLYNXAJCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDENRRGUYDGOJTGU>.
You are receiving this because you were mentioned.

2024-08-01 12:07 UTC, lrpablo commented on oclmath/rounding_mode.cpp
> +        #error Unknown arch 1
Should not have been there

2024-08-01 12:14 UTC, closed without merging

2024-08-01 18:45 UTC, bader commented
> Do you have an estimated date for when it will be present in the release?

SYCL-CTS project doesn't have releases, so you can use the head of the SYCL-2020 branch to validate your favorite SYCL implementation.
With regards to https://github.com/KhronosGroup/SYCL-CTS/pull/890, PRs are merged once they are approved and pass pre-commit validation. I'll try to facilitate the code review process.